package Encapsulation;

public class ObjfvEmpMain {
	public static void main(String[] args) {
		ObjfiveEmp emp1 = new ObjfiveEmp();
		emp1.setId(1);// System.out.println(emp1.id);
		emp1.setSalary(45000);
		emp1.setName("pooja");
		emp1.setDept("Electronics");
		emp1.setContact("9876543210");
		System.out.println("employee id:" + emp1.getId());
		System.out.println("employee salary:" + emp1.getSalary());
		System.out.println("employee name:" + emp1.getName());
		System.out.println("employee department:" + emp1.getDept());
		System.out.println("employee contact number:" + emp1.getContact());
		System.out.println();
		ObjfiveEmp emp2 = new ObjfiveEmp();
		emp2.setId(2);// System.out.println(emp2.id);
		emp2.setSalary(40000);
		emp2.setName("rutu");
		emp2.setDept("bcs");
		emp2.setContact("9876543210");
		System.out.println("employee id:" + emp2.getId());
		System.out.println("employee salary:" + emp2.getSalary());
		System.out.println("employee name:" + emp2.getName());
		System.out.println("employee department:" +emp2.getDept());
		System.out.println("employee contact number:" +emp2.getContact());
		System.out.println();
		ObjfiveEmp emp3 = new ObjfiveEmp();
		emp3.setId(3);// System.out.println(emp3.id);
		emp3.setSalary(90000);
		emp3.setName("rahul");
		emp3.setDept("entc");
		emp3.setContact("9876543210");
		System.out.println("employee id:" + emp3.getId());
		System.out.println("employee salary:" + emp3.getSalary());
		System.out.println("employee name:" + emp3.getName());
		System.out.println("employee department:" +emp3.getDept());
		System.out.println("employee contact number:" +emp3.getContact());
		System.out.println();
		ObjfiveEmp emp4 = new ObjfiveEmp();
		emp4.setId(4);// System.out.println(emp4.id);
		emp4.setSalary(30000);
		emp4.setName("prajkta");
		emp4.setDept("bpharmacy");
		emp4.setContact("9876543210");
		System.out.println("employee id:" + emp4 .getId());
		System.out.println("employee salary:" + emp4 .getSalary());
		System.out.println("employee name:" +emp4 .getName());
		System.out.println("employee department:" + emp4 .getDept());
		System.out.println("employee contact number:" + emp4 .getContact());
		System.out.println();
		ObjfiveEmp emp5 = new ObjfiveEmp();
		emp5.setId(5);// System.out.println(emp5.id);
		emp5.setSalary(40000);
		emp5.setName("sandip");
		emp5.setDept("bsc");
		emp5.setContact("9876543210");
		System.out.println("employee id:" +emp5.getId());
		System.out.println("employee salary:" + emp5.getSalary());
		System.out.println("employee name:" + emp5.getName());
		System.out.println("employee department:" +emp5.getDept());
		System.out.println("employee contact number:" +emp5.getContact());
	}
	}
//System.out.println("employee id:"+emp1.getId()+"\n"+"employee salary:"+emp1.getSalary()+"\n"+"employee name:"+emp1.getName()+"\n"+"employee department:"+emp1.getDept()+"\n"+"employee contact number:"+emp1.getContact());
//System.out.println("employee id:"+emp2.getId()+"\n"+"employee salary:"+emp2.getSalary()+"\n"+"employee name:"+emp2.getName()+"\n"+"employee department:"+emp2.getDept()+"\n"+"employee contact number:"+emp2.getContact());
//System.out.println("employee id:"+emp3.getId()+"\n"+"employee salary:"+emp3.getSalary()+"\n"+"employee name:"+emp3.getName()+"\n"+"employee department:"+emp3.getDept()+"\n"+"employee contact number:"+emp3.getContact());
//System.out.println("employee id:"+emp4.getId()+"\n"+"employee salary:"+emp4.getSalary()+"\n"+"employee name:"+emp4.getName()+"\n"+"employee department:"+emp4.getDept()+"\n"+"employee contact number:"+emp4.getContact());
//System.out.println("employee id:"+emp5.getId()+"\n"+"employee salary:"+emp5.getSalary()+"\n"+"employee name:"+emp5.getName()+"\n"+"employee department:"+emp5.getDept()+"\n"+"employee contact number:"+emp5.getContact());
